FROM ubuntu

RUN apt-get update

RUN apt-get -y install ffmpeg

RUN apt-get -y install wget

RUN apt-get -y install python3

WORKDIR /music/Muzic_Manager

RUN wget http://ftp.cn.debian.org/debian/pool/main/y/youtube-dl/youtube-dl_2021.12.17-1_all.deb

RUN apt -y install ./youtube-dl_2021.12.17-1_all.deb

COPY config.txt /root/.bashrc

ENTRYPOINT ["bash"]